---
title: "hw_dottable"
author: "Jack Kuo Chang"
date: "2025-03-02"
output: pdf_document
---

```{r, message = FALSE}
setwd("~/hw_dottable")
library(tidyverse)
library(dplyr)
library(data.table)
nycdata <- fread("nycdata.csv") 
#link: https://github.com/jkuoc183/hw_dottable
#ssh: git@github.com:jkuoc183/hw_dottable.git
```

```{r}
#1.	Use and show data.table code to select the variables year, month, day, and hour from the imported flights data
nycdata_col <- nycdata[ , .(year, month, day, hour)]
head(nycdata_col)
```

```{r}
#2. Use and show data. table code to produce a table that shows a carrier of DL, an origin of JFK and a destination of SEA

dl_jfk_sea <- nycdata[carrier == "DL" & origin =="JFK" & dest =="SEA"]
head(dl_jfk_sea)
```


```{r}
#3.	Use and show data.table code to produce a table that shows a carrier of UA, a month of March, and an airtime that is below 330.
ua_march_airtime <- nycdata[carrier == "UA" & month == 3 & air_time < 330]
head(ua_march_airtime)
```


```{r}
#4.	Use and show tidyverse code to produce a table that shows a carrier of UA, a month of March, and an airtime that is below 330.
ua_march_airtime_tidy <-  nycdata |> 
  filter(carrier == "UA", month == 3, air_time < 330)
head(ua_march_airtime_tidy)
```


```{r}
#5. Use the data.table method to add a variable called speed that is the average air speed of the plane in miles per hour.
nycdata[ , speed := round(distance/(air_time/60),2)]
head(nycdata)
```


```{r}
#6.	Use the tidyverse method to add a variable called speed that is the average air speed of the plane in miles per hour.
nycdata<- nycdata |> 
  mutate(speed = round(distance/ (air_time/60),2))
head(nycdata)

```

```{r}
#7.	Show and use coding to change the carrier abbreviation of UA to UnitedAir,
#7a. data.table method
nycdata[carrier == "UA", carrier := "UnitedAir"]
unique(nycdata$carrier)

```

```{r}
#7b. tidyverse method (Use a sequence of dplyr commands so that you can see the change in your table)

nycdata <- nycdata |> 
 mutate(carrier = ifelse(carrier == "UA", "UnitedAir",carrier))
nycdata |> 
  count(carrier)
```